for i in '1000' '2000' '3000'
do
./build/visualizers/view_network.bin ../aravindhm_caffe/sparseconvautoencoder/net_deploy_manykernels.txt /snapshots/sparseconvautoencoder/caffe_sparseconvautoencoder_train_lr05_step500_gamma9_momentum9_wdecay0005_verylargeeuclideanloss_lowl1sparse_manykernels_stride4_moderatelr_iter_$i sparseautoencoder/lr05verylargelosslowl1sparsemanykernelsstride4moderatelr/iter$i/
mkdir -p /opt/www/sparseautoencoder/lr05verylargelosslowl1sparsemanykernelsstride4moderatelr/iter$i/
mv *.png /opt/www/sparseautoencoder/lr05verylargelosslowl1sparsemanykernelsstride4moderatelr/iter$i/
mv index.html /opt/www/sparseautoencoder/lr05verylargelosslowl1sparsemanykernelsstride4moderatelr/iter$i/
done
